# Starship configuration - matches your existing # prompt style
format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$character"""

[character]
success_symbol = "[#](bold blue)"
error_symbol = "[#](bold red)"

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = false

[git_branch]
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold red"
format = '([\[$all_status$ahead_behind\]]($style) )'

[nodejs]
style = "bold green"
format = "[$symbol($version)]($style) "

[python]
style = "bold yellow"
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
